<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-02T14:59:40 IST" name="Suite" finished-at="2022-07-02T15:00:31 IST" duration-ms="50104">
    <groups>
    </groups>
    <test started-at="2022-07-02T14:59:40 IST" name="Test_All" finished-at="2022-07-02T15:00:31 IST" duration-ms="50104">
      <class name="com.MySeleniumProject_2.testcases.CompleteVerificationScenario">
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:com.MySeleniumProject_2.testcases.CompleteVerificationScenario@2accdbb5]" started-at="2022-07-02T14:59:40 IST" name="loadConfig" finished-at="2022-07-02T14:59:40 IST" duration-ms="618" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.MySeleniumProject_2.testcases.CompleteVerificationScenario@2accdbb5]" started-at="2022-07-02T14:59:41 IST" name="setup" finished-at="2022-07-02T14:59:44 IST" duration-ms="3056" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="completeVerification(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.MySeleniumProject_2.testcases.CompleteVerificationScenario@2accdbb5]" started-at="2022-07-02T14:59:44 IST" name="completeVerification" data-provider="User_Details" finished-at="2022-07-02T15:00:06 IST" duration-ms="21558" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[xyz]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9999.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [THANK YOU FOR YOUR ORDERSSSS] but found [THANK YOU FOR YOUR ORDER]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [THANK YOU FOR YOUR ORDERSSSS] but found [THANK YOU FOR YOUR ORDER]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.MySeleniumProject_2.testcases.CompleteVerificationScenario.completeVerification(CompleteVerificationScenario.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- completeVerification -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.MySeleniumProject_2.testcases.CompleteVerificationScenario@2accdbb5]" started-at="2022-07-02T15:00:06 IST" name="tearDown" finished-at="2022-07-02T15:00:06 IST" duration-ms="392" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.MySeleniumProject_2.testcases.CompleteVerificationScenario@2accdbb5]" started-at="2022-07-02T15:00:06 IST" name="setup" finished-at="2022-07-02T15:00:09 IST" duration-ms="2529" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="completeVerification(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.MySeleniumProject_2.testcases.CompleteVerificationScenario@2accdbb5]" started-at="2022-07-02T15:00:09 IST" name="completeVerification" data-provider="User_Details" finished-at="2022-07-02T15:00:30 IST" duration-ms="20989" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[qwe]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[asd]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[8888.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [THANK YOU FOR YOUR ORDERSSSS] but found [THANK YOU FOR YOUR ORDER]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [THANK YOU FOR YOUR ORDERSSSS] but found [THANK YOU FOR YOUR ORDER]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.MySeleniumProject_2.testcases.CompleteVerificationScenario.completeVerification(CompleteVerificationScenario.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- completeVerification -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.MySeleniumProject_2.testcases.CompleteVerificationScenario@2accdbb5]" started-at="2022-07-02T15:00:30 IST" name="tearDown" finished-at="2022-07-02T15:00:31 IST" duration-ms="433" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="afterSuite1()[pri:0, instance:com.MySeleniumProject_2.testcases.CompleteVerificationScenario@2accdbb5]" started-at="2022-07-02T15:00:31 IST" name="afterSuite1" finished-at="2022-07-02T15:00:31 IST" duration-ms="298" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite1 -->
      </class> <!-- com.MySeleniumProject_2.testcases.CompleteVerificationScenario -->
    </test> <!-- Test_All -->
  </suite> <!-- Suite -->
</testng-results>
